### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by Remypoc** [Bouquet2/AssoGenda#5]
Error : no sdk version 23

**Comment by vbouquet** [comment]
It is not possible to completely automated gradle build if sdk is missing.

- First you must have either a local.properties file with following content: "sdk.dir={$PATH/SDK}" in your project folder or an environment variable ANDROID_HOME pointing to your SDK location.

- Second, according to official documentation (https://developer.android.com/studio/intro/update.html#download-with-gradle) it is possible to download SDK only if you accepted licences before via SDK manager.

I will update installation instructions accordingly.
